package gmit;
import java.util.*;

public class CountryNames {

    public void fillEuropeList(List<String> countryNames){
        countryNames.add("Ireland");
        countryNames.add("England");
        countryNames.add("Germany");
        countryNames.add("Wales");
        countryNames.add("Scotland");
        countryNames.add("France");
        countryNames.add("Belgium");
        countryNames.add("Holland");
        countryNames.add("Spain");
        countryNames.add("Portugal");
        countryNames.add("Poland");
        countryNames.add("Czech Rep");
        countryNames.add("Slovakia");
        countryNames.add("Austria");
        countryNames.add("Monaco");
        countryNames.add("Hungary");
        countryNames.add("Romania");
        countryNames.add("Moldova");
        countryNames.add("Italy");
        countryNames.add("Greece");
        countryNames.add("Albania");
        countryNames.add("Bulgaria");
        countryNames.add("Russia");
        countryNames.add("Ukraine");
        countryNames.add("Iceland");
        countryNames.add("Sweden");
        countryNames.add("Denmark");
        countryNames.add("Finland");
        countryNames.add("Andorra");
        countryNames.add("Armenia");
        countryNames.add("Azerbaijan");
        countryNames.add("Belarus");
        countryNames.add("Bosnia");
        countryNames.add("Croatia");
        countryNames.add("Cyprus");
        countryNames.add("Estonia");
        countryNames.add("Georgia");
        countryNames.add("Kazakhstan");
        countryNames.add("Kosovo");
        countryNames.add("Latvia");
        countryNames.add("Liechtenstein");
        countryNames.add("Lithuania");
        countryNames.add("Luxembourg");
        countryNames.add("Macedonia");
        countryNames.add("Malta");
        countryNames.add("Montenegro");
        countryNames.add("Norway");
        countryNames.add("San Marino");
        countryNames.add("Serbia");
        countryNames.add("Slovenia");
        countryNames.add("Switzerland");
        countryNames.add("Turkey");
        countryNames.add("Vatican City");
    } // End fillEuropeList method

    
    public void fillAfricaList(List<String> countryNames){
        countryNames.add("Algeria");
        countryNames.add("Angola");
        countryNames.add("Benin");
        countryNames.add("Botswana");
        countryNames.add("Burkina Faso");
        countryNames.add("Burundi");
        countryNames.add("Cape Verde");
        countryNames.add("Cameroon");
        countryNames.add("Central African Rep");
        countryNames.add("Chad");
        countryNames.add("Comoros");
        countryNames.add("Dem Congo");
        countryNames.add("Rep Congo");
        countryNames.add("Ivory Coast");
        countryNames.add("Djibouti");
        countryNames.add("Egypt");
        countryNames.add("Eq Guinea");
        countryNames.add("Eritrea");
        countryNames.add("Ethiopia");
        countryNames.add("Gabon");
        countryNames.add("Gambia");
        countryNames.add("Ghana");
        countryNames.add("Guinea");
        countryNames.add("Guinea-Bissau");
        countryNames.add("Kenya");
        countryNames.add("Lesotho");
        countryNames.add("Liberia");
        countryNames.add("Libya");
        countryNames.add("Madagascar");
        countryNames.add("Malawi");
        countryNames.add("Mali");
        countryNames.add("Mauritania");
        countryNames.add("Mauritius");
        countryNames.add("Morocco");
        countryNames.add("Mozambique");
        countryNames.add("Namibia");
        countryNames.add("Niger");
        countryNames.add("Nigeria");
        countryNames.add("Rwanda");
        countryNames.add("Sao Tome and Principe");
        countryNames.add("Senegal");
        countryNames.add("Seychelles");
        countryNames.add("Sierra Leone");
        countryNames.add("Somalia");
        countryNames.add("South Africa");
        countryNames.add("South Sudan");
        countryNames.add("Sudan");
        countryNames.add("Swaziland");
        countryNames.add("Tanzania");
        countryNames.add("Togo");
        countryNames.add("Tunisia");
        countryNames.add("Uganda");
        countryNames.add("Zambia");
        countryNames.add("Zimbabwe");
    } // End fillAfricaList method
}